services:
  
  client:
    container_name: fsp-client
    restart: always
    tty: true
    build: ./client
    ports:
      - "3000:3000"
    links:
      - server
    networks:
      - fsp-network

  server:
    container_name: fsp-server
    restart: always
    build: ./server
    ports:
      - "4000:4000"
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - fsp-network

  mongo:
    container_name: mongo
    image: mongo:5.0.3
    ports:
      - "27017:27017"
    networks:
      - fsp-network

networks:
  fsp-network:
    driver: bridge
